pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your Git repository with the 'main' branch
                checkout([$class: 'GitSCM', branches: [[name: 'master']], userRemoteConfigs: [[url: 'https://github.com/michTalebzadeh/rhes75_GCP.git']]])
            }
        }

        stage('Terraform Init') {
            steps {
                // Initialize Terraform (downloads necessary plugins and modules)
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                // Create a Terraform plan
                sh 'terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                // Apply the Terraform plan to create the resources
                sh 'terraform apply -auto-approve tfplan'
            }
        }

        stage('Terraform Destroy') {
            steps {
                // If needed, you can add a stage to destroy the resources
                echo 'Build succeeded, change line to destroy it'
                // sh 'terraform destroy -auto-approve'
            }
        }
    }

    post {
        success {
            echo 'Build succeeded' // This will print 'Build succeeded' in the console
        }

        failure {
            echo 'Build failed' // This will print 'Build failed' in the console
        }
    }
}

